# .github/workflows/ci.yml
name: CI
on: [push, pull_request]
jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: python -m pip install -U pip build
      - run: python -m pip install -e .[dev]
      - run: pytest -q
      - run: ruff check .
      - run: black --check .
      - run: mypy src
      - run: python -m build
