[theme]
base = "dark"
primaryColor = "#4C78A8"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = false
address = "localhost"
port = 8501

[logger]
level = "info"
