# Theme (tweak to taste)
[theme]
base = "dark"                # or "light"
primaryColor = "#4C78A8"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

# Privacy / telemetry
[browser]
gatherUsageStats = false

# Server (friendly defaults for local + container)
[server]
headless = true
address = "0.0.0.0"         # allows access from containers/other devices
port = 8501
maxUploadSize = 200          # MB; bump if you need larger uploads

# Logging verbosity (optional)
[logger]
level = "info"
